config/routes.rb
Rails.application.routes.draw do

  root 'videos#homepage'

  get 'videos/new' => 'videos#new'
  post 'videos/create' => 'videos#create'
  get 'videos/view/:id' => 'videos#view', as: :video_view
  get 'videos/list' => 'videos#list', as: :video_list

  post 'users/login' => 'users#login', as: :login
  get 'users/sign_in' => 'users#sign_in', as: :sign_in
  get 'users/logout' => 'users#logout', as: :logout
  get 'profile/(:username)' => 'users#profile', as: :profile
  post 'profile/save' => 'users#save_profile', as: :save_profile
  get 'edit_profile' => 'users#edit_profile', as: :edit_profile
  get 'register' => 'users#register', as: :register
  post 'new_user' => 'users#new_user', as: :new_user
  post 'playlist/new' => 'playlists#new', as: :new_playlist
  post 'playlist/add_video' => 'playlists#add_video', as: :playlist_add_video
  get 'playlists' => 'playlists#list', as: :playlists
  get 'playlist/:name' => 'playlists#show', as: :playlist
  post 'change_video_place/:playlist/:video/:new_place' => 'playlists#change_video_place', as: :change_video_place

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

	def add_video(video)
		pe = PlaylistEntry.new

		pe.video = video
		pe.playlist = self

		# no entries, first one is number 0
		# one entrie, second one is number 1
		# etc... we get a neat 0-indexed ordering list
		pe.sequence = self.playlist_entries.count
		pe.save
	end

	def videos
		vids = []
		self.playlist_entries.each do |entry|
			vids << entry.video
		end

		return vids
	end

	def move_video(video_id, new_position)

		# sanity check
		new_position = Integer(new_position)
		if new_position < 0 or new_position > (playlist_entries.count - 1)
			return false
		end

		# if we're moving the video up the list, than those before it and after the 
		# new spot need to go down one position each, and vice-versa for moving down the list

		entry = playlist_entries.find_by(video_id: video_id)		

		if new_position > entry.sequence
			#move down
			entries_to_move = playlist_entries.where("sequence > ? AND sequence <= ? ", entry.sequence, new_position)

			entries_to_move.each do |e|
				e.sequence = e.sequence - 1
				e.save
			end
		elsif new_position < entry.sequence
			#move up
			entries_to_move = playlist_entries.where("sequence < ? AND sequence >= ?", entry.sequence, new_position)

			entries_to_move.each do |e|
				e.sequence = e.sequence + 1
				e.save
			end
		else
			#do nothing
		end

		# set the sequence of the entry to the desired value
		entry.sequence = new_position
		
		return entry.save			
	end


	has_many :playlist_entries
	belongs_to :user
end

app/models/playlist_entry.rb
class PlaylistEntry < ActiveRecord::Base
	default_scope do 
		order "sequence"
	end


	belongs_to :video
	belongs_to :playlist
end

app/models/user.rb
require 'digest/sha1' 
class User < ActiveRecord::Base

  has_attached_file :avatar,
    path: Rails.application.config.paperclip_path,
    url: Rails.application.config.paperclip_url,
    styles: {
      thumbnail: ["320x180", :png]
    }

  validates_attachment :avatar,
    content_type: {
      content_type: /^image\/(jpg|gif|png|jpeg)/
    }

  has_attached_file :cover,
    path: Rails.application.config.paperclip_path,
    url: Rails.application.config.paperclip_url,
    styles: {
      thumbnail: ["320x180", :png]
    }

  validates_attachment :cover,
    content_type: {
      content_type: /^image\/(jpg|gif|png|jpeg)/
    }

  def password=(pw)
    self.password_hash = Digest::SHA1.hexdigest(pw)
  end

  def password_match(pw)
    if self.password_hash == Digest::SHA1.hexdigest(pw)
      return true
    else
      return false
    end
  end

  has_many :playlists
  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :video_file,
    path: Rails.application.config.paperclip_path,
    url: Rails.application.config.paperclip_url,
    styles: {
      thumbnail: ["320x180", :png]
    },
    processors: [:video_thumbnail]

  validates_attachment :video_file,
    content_type: {
      content_type: /^video\/(mp4|ogg|webm)/
    }


  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    else
      return nil
    end
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end


  # could not write a test for this - need to find a way to do it
  def users_only
    unless logged_in?
      redirect_to(:sign_in)
      return false
    end

    return true
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
	def new
		users_only or return
		@playlist = Playlist.new
		@playlist.name = params[:name]

		@playlist.user = current_user
		@playlist.save
	end

	def add_video
		users_only or return

		pl=current_user.playlists.find(params[:playlist])

		pl.add_video(Video.find(params[:video]))


		
		# double logged in check because the redirect in users_only method does not
		# halt the execution, hence redirect is called twice and its a no-no in Rails
		if logged_in?
			redirect_to playlist_path(name: pl.name)
		end		
	end

	def list
		@playlists = current_user.playlists
	end

	def show
		@plist = Playlist.find_by(name: params[:name])
	end

	def change_video_place
		users_only or return
		plist = current_user.playlists.find(params[:playlist])

		if plist.move_video(params[:video], params[:new_place])
			redirect_to playlist_path(plist.name)
		else
			return head(:forbidden)
		end

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    user = User.find_by email: params[:email]

    if user
      if user.password_match(params[:password])
        session[:user_id] = user.id
        redirect_to :video_list
      else
        redirect_to :sign_in
      end
    else
      redirect_to :sign_in
    end
  end

  def sign_in
    @user = User.new
  end

  def logout
    session[:user_id] = nil
    redirect_to :sign_in
  end

  def profile
    unless params[:username].nil?
      @user = User.find_by(username: params[:username])
    else
      @user = current_user
    end
  end

  def edit_profile
    users_only or return
    @user = current_user
  end

  def save_profile
    users_only or return
    @user = current_user


    @user.avatar = params[:avatar] unless params[:avatar].nil?
    @user.cover = params[:cover] unless params[:cover].nil?
    @user.email = params[:email] unless params[:email].nil?
    @user.title = params[:title] unless params[:title].nil?
    @user.description = params[:description] unless params[:description].nil?
    @user.username = params[:username] unless params[:username].nil?
    @user.password = params[:password] unless params[:password].nil?

    @user.save

    redirect_to :profile
  end

  def register
    # just shows the registration page :)
  end

  def new_user
    u = User.new

    u.email = params[:email]
    u.password = params[:password]

    u.save

    session[:user_id] = u.id # manual log in

    redirect_to :profile
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    users_only
    @video = Video.new  
  end

  def create
    users_only or return
    @video = Video.new

    @video.title = params[:video][:title]
    @video.description = params[:video][:description]
    @video.video_file = params[:video][:file]
    @video.user = current_user

    @video.save
  end

  def view
    @video = Video.find(params[:id])
    @video.view_count += 1
    @video.save
    @user = current_user

    @related_videos = @video.user.videos
  end

  def list
    @videos = Video.all
  end

  def homepage
    @latest_videos = Video.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment_section.html.erb
    <section id="comments">
      <h2>Comments:</h2>
      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>

      <div class="comment">
        <h4>Anonymous:</h4>
        <p>
          ncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        </p>
      </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideosAndComments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no" />
</head>
<body>
<header>
  <nav>
    <div id="site_sections">
      <a href="/">Home</a>
      <a href="/">Newest</a>
      <a href="/">Reccomended</a>
      <a href="/">About</a>
    </div>

    <div id="user_profile">
      <a href="/users/sign_in">Login</a>
    </div>
	</nav>
</header>

<%= yield %>

</body>
</html>

app/views/playlists/list.html.erb
<% @playlists.each do |plist| %>
	<li><%= link_to plist.name, playlist_path(plist.name) %></li>
<% end %>

<p>
	<form action="<%= new_playlist_path() %>" method="post">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<label for="name">Name for your playlist</label>
		<input type="text" name="name" id="name">
		<input type="submit" value="Create">
	</form>
</p>

app/views/playlists/new.html.erb
<h1>You made a brand new playlist, hoooray</h1>

app/views/playlists/show.html.erb
<% @plist.videos.each do |vid| %>
	<%= link_to image_tag(vid.video_file.url(:thumbnail)), video_view_path(vid.id) %>
<% end %>

app/views/users/edit_profile.html.erb
<h1>Edit your profile</h1>
<form action="profile/save" method="post" enctype="multipart/form-data">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<label for="avatar">Your avatar image:</label>
	<input type="file" name="avatar" id="avatar">

	<label for="cover">Your profile cover image:</label>
	<input type="file" name="cover" id="cover">
	
	<label for="email">email:</label>
	<input type="text" name="email" id="email" value="<%= @user.email %>">
	
	<label for="username">username:</label>
	<input type="text" name="username" id="username" value="<%= @user.username  %>">
	
	<label for="title">title:</label>
	<input type="text" name="title" id="title" value="<%= @user.title  %>">
	
	<label for="description">description:</label>
	<input type="text" name="description" id="description" value="<%= @user.description  %>">
	
	<label for="pass">password:</label>
	<input type="password" name="password" id="password">
	
	<input type="submit">
</form>

app/views/users/profile.html.erb
<h1><%= @user.title %></h1>
<h2><%= @user.description  %></h2>


<%= image_tag @user.avatar.url %>
<%= image_tag @user.cover.url %>

<p>by: <%= @user.username %></p>
<p><%= @user.email %></p>

<%= link_to "Edit", edit_profile_path %>

app/views/users/register.html.erb
<h1>Register a new account! so exciting</h1>
<form action="new_user" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<label for="email">email:</label>
	<input type="text" name="email" id="email">
	<label for="pass">password:</label>
	<input type="password" name="password" id="password">
	<input type="submit">
</form>

app/views/users/sign_in.html.erb
<h1>Sign in pls</h1>
<form action="login" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<label for="email">email:</label>
	<input type="text" name="email" id="email">
	<label for="pass">password:</label>
	<input type="password" name="password" id="password">
	<input type="submit">
</form>

app/views/videos/_video_card.html.erb
	<div class="video_card">
		<%= link_to video_view_path(video.id) do %>
			<h3><%= video.title %></h3>
			<%=image_tag(video.video_file.url(:thumbnail)) %>
			<p><%= video.description %></p>
		<% end %>
	</div>

app/views/videos/homepage.html.erb
<main id="homepage">
	<header>
		<h1>VidSite</h1>
		<em>HTML5</em>
		<p>mobile device compatible</p>
		<p>no flash</p>
	</header>

	<section id="latest_videos">
		<h2>Latest videos:</h2>
		<% @latest_videos.each do |video| %>
			<%= render "video_card", video: video %>
		<% end %>
	</section>
</main>

app/views/videos/list.html.erb
<h1>list of videos</h1>

<% @videos.each do |video| %>
  <%= link_to image_tag(video.video_file.url(:thumbnail)), video_view_path(video.id) %>
<% end %>

app/views/videos/new.html.erb
<h1>lol</h1>
<form action="create" method="post" enctype="multipart/form-data">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="video[title]">
  <input type="text" name="video[description]">
  <input type="file" name="video[file]">
  <input type="submit">
</form>

app/views/videos/view.html.erb
<main id="view_video">

  <section id="video_area">
    <video id="video" class="video-js" controls preload="auto" data-setup="{}">
      
      <source src="<%= @video.video_file.url %>" type="video/webm">

       <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>
  </section>

  <section id="additional_content">
    <section id="details">
      <div id="basic_info">
        <h1><%= @video.title %></h1>
        <p>
          by: <%= @video.user.email %>
        </p>
      </div>

      <div id="stats">
        <p>
          watched <em><%= @video.view_count %></em> times
        </p>
      </div>

      <div id="description">
        <%= @video.description %>
      </div>
    </section>
    
    <%= render "comments/comment_section" %> 

  </section>


  <section id="related_videos">
    <% @related_videos.each do |video| %>
      <%= render "video_card", video: video %>
    <% end %>
  </section>

  

  <ul>
  <% if @user %>
    <p>Add to playlist:</p>
  	<% @user.playlists.each do |plist| %>
  		<li><%= link_to plist.name, playlist_add_video_path(playlist: plist.id, video: @video.id), method: :post %></li>
  	<% end %>
  <% end %>
  </ul>
</main>